/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 04 12:12:22 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExamESTest extends Exam_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Exam exam0 = new Exam();
      int int0 = exam0.grade(false, 55);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Exam exam0 = new Exam();
      int int0 = exam0.grade(false, 60);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Exam exam0 = new Exam();
      int int0 = exam0.grade(false, 80);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Exam exam0 = new Exam();
      int int0 = exam0.grade(false, 90);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Exam exam0 = new Exam();
      int int0 = exam0.grade(false, 100);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Exam exam0 = new Exam();
      int int0 = exam0.grade(true, 0);
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Exam exam0 = new Exam();
      int int0 = exam0.grade(false, 1);
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Exam exam0 = new Exam();
      int int0 = exam0.grade(false, 50);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Exam exam0 = new Exam();
      int int0 = exam0.grade(false, 75);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Exam exam0 = new Exam();
      // Undeclared exception!
      try { 
        exam0.grade(true, 3936);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // invalid points
         //
         verifyException("Exam", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Exam exam0 = new Exam();
      int int0 = exam0.grade(false, 62);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Exam exam0 = new Exam();
      // Undeclared exception!
      try { 
        exam0.grade(false, (-1921));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // invalid points
         //
         verifyException("Exam", e);
      }
  }
}
